# Mindful infrastructures and their re-concatenation of worlds

After George Osborne (UK Chancellor of the Exchequer), Boris Johnson (Mayor of London), _The Evening Standard_ listed Demis Hassabis as 2014's most influential Londoner <http://www.standard.co.uk/news/the1000/the-1000--londons-most-influential-people-2014-tech-stars-9780818.html>. Hassabis started a company called DeepMind in 2011. After completing his PhD in neuroscience sometime in 2011, Hassabis, erstwhile computer game designer, world gaming champion, chess master and artificial intelligence expert, had in 2014 started working for the Google Corporation. Google paid £400 million for DeepMind, the company Hassabis started with two others in 2011. DeepMind has no products, but it had managed to construct neural networks that _learned_ to play early 1980s Atari computer games [@Mnih_2013]. This game-playing performance motivated Google's purchase. As is well known, Google has had a long standing commitment to data mining, machine learning and artificial intelligence in general in their bid to "organise the world's information" <https://www.google.co.uk/about/company/>. Reportedly, Hassabis' DeepMind work at Google is already shaping search engine results [@Levy_2015]. 

All of this might seem to lie a long way from roads, water and sanitation, energy or transport infrastructures of modernity. Or does it? Two things might motivate us to reassess that sense of distance between infrastructural modernity and the digital revolutions, one of whose cutting edges Hassabis personifies.  

(1) If Hassabis, the computer geek, comes after the Johnson, the city mayor responsible for transport, waste, etc. in the global city of London, and after Osborne, the government minister responsible for national finance and economic management, then there might be an infrastructural logic that connects them. What could the cutting edge of digital infrastructure, that takes the form of predictive modelling, tell us about the materiality, the temporality, the forms of subjectivation, power relations or publics associated with infrastructure more generally? Might we say that after the infrastructures of State (UK), urbanisation (London), come the promise of mindful infrastructures.

(2) Google's purchase of Hassabis' DeepMind is not an isolated case of the melding of information infrastructures with data mining, pattern recognition or machine learning techniques. We could turn to IBM's Watson, an enterprise artificial intelligence that first shot to prominence by winning the US TV quiz show 'Jeopardy' in 2011. In the years since, Watson has been networked,  re-tooled and infrastructuralised as a  'cognitive computing' assemblage whose Ecosystem has, with the help of \$1 billion investment and a team of several thousand technical and marketing personnel, rapidly penetrated elite medical institutions such as the Mayo Clinic or the Sloan Kettering Memorial Cancer Institute, and has wedded itself to insurance, higher education, the health industry, various scientific fields (notably genomics) and cooking, amongst other things. The financialised leveraging of these approaches is also well evidenced in the case of HP Autonomy. Autonomy, one of the UK's largest and most profitable software businesses, was bought by HP for £7.4 billion (\$10 billion) in 2011 on the basis of its Bayesian pattern recognition techniques (also branded as 'meaning-based computing', themselves allied with researchers in computer science at Cambridge). Within months, HP 'wrote down' the value of its acquisition by around \$8 billion, claiming accounting improprieties. Despite these accounting difficulties and ongoing litigation, HP has integrated the key components of 'meaning-based computing' into its many faceted utility, healthcare, transport, call-centre management, data management, operations management, patient records, legal support, security and intelligence products.  

DeepMind, Watson and Autonomy have something in common. They are all highly 'mindful,' and abound in references to cognition, meaning, perception, sense data, hearing, speaking, seeing, remembering, deciding, and surprisingly, imagining and fantasy. They are all polymorphous figures of infrastructural reorganisation around the ideal of something like pattern recognition or prediction. This is no longer the statistical rendering of number in the hands of government, science or commerce, as in William Gosset's construction of _Student's t-test_ for monitoring Guinness stout quality in Dublin in the early 20th century [@Porter_2008; @Hacking_1990], nor the intricate interweaving of classification systems and things that grew into a forest of operational standards during the course of the last century[@Bowker_1999].  DeepMind, Watson and Autonomy each seriously address the relation between humans and infrastructures, not so much as a matter of imagining [@Mackenzie_2003], practice, configuration [@Suchman_2006], or repair [@Graham_2007] as a matter of mind, brain, and cognitive challenge.   Watson, DeepMind and Autonomy present problems of seeing, hearing, checking and comparing as no longer the province of human operators, experts, professionals or workers seeking to navigate and finesse the constraints, limitations, breakdowns and vicissitudes of infrastructures, but as matters for an often almost Cyclopean  cognition to reorganise and optimise in a kind of experimental, competitive challenge. The initial training of DeepMind to play a half-dozen Atari computer games (from the early 1980s) or Watson to win  _Jeopardy_ directly point at this orientation towards challenges amidst competition, disconnectedness and disparity.

Would it be safe to say that these kinds of cognitive infrastructures, with their appetite for data and their ambition to reorganise other infrastructures (e.g. Google's Self-Driving Car or its acquisition of the home thermostat company Nest; etc.), are the excrescence of somewhat techno-cosmological imaginaries of Silicon Valley engineers and the like? Yes, but they powerfully  subduct [@Mackenzie_2012] existing infrastructures. On the one hand, the centres of calculation that Google or HP make and manage are effectively global assemblages [@Ong_2005], with specific administrative, commercial, engineering and scientific apparatuses and regimes of value. On the other hand, the increasing 'mindfulness' of the infrastructures under construction at IBM, Google and the like predicate a certain re-concatenation of the world, no longer in the mobile train of experience of people moving through streets, houses, factories and offices, but instead in the relations mindfully discerned in streams of data. We well know that information systems have a kind of various appetite for expansion. They are contagious infrastructures. And the study of venture capital investments in Silicon Valley startups or the serial acquisitions of start-up companies by IT giants such as Microsoft, IBM, HP or Google is familiar. But the mode of existence of contemporary infrastructures might be changing shape as a certain kind of 'mindfulness' is brought to bear on the scattered, partial and disaggregate worlds, themselves partly a product of the splintering of infrastructural modernity [@Marvin_2001], as well as the device-specific intensities of 'knowing capitalism' [@Thrift_2005]. 

The 3rd most influential person in London, 2014, works on data, infrastructures, games and brains

TBC -- google's way of provisioning infrastructure -- cheap commodity hardware + experimental management
-- the repurposing of GPUs + the revitalisation of neural nets -- these mattered a lot to philosophers of mind and cognitive scientists, but were overtaken by svms
-- the brain, the hippocampus, etc. (cognition, meaning, mind)
-- the atari games, and the example of deepmind playing pong in a way that exploits the systems weakness: one system finds something in another system - is this an infrastructural icon ... 
-- resurrection of AI will mean what? lots of work for philosophers, sociologists and anthropologists trying to understand what happens to Theo in _Her_?0
- Google already had Ng, Thrun, Hinton and the Ray Kurzweil ... 
